In [1]:
 import numpy as np
c=np.linspace(5,10,5)
c

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
d=np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x=np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
y=np.eye(3)#creates a matrix with 1 as diagonals
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
z=np.eye(3,2)
z

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
a=np.diag([1,2,3,4])#constructs a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(a)#extracts diagonal elements

array([1, 2, 3, 4])

In [ ]:
a=np.random.rand(4)
a

array([0.04461629, 0.44110311, 0.42974902, 0.13019128])

## DataType

In [ ]:
a=np.arange(10,dtype='float')
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
b=np.array([1+2j,5+1j])
print(b.dtype)

complex128


In [ ]:
c=np.array([True,False,True])
print(c.dtype)

bool


# Indexing and slicing

## Indexing

In [ ]:
a=np.arange(10)
print(a)
print(a[5])
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
5
9


In [ ]:
b=np.diag([1,2,3])
print(b)
print(b[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [ ]:
b[2,1]=10#assining a value to index
print(b)

[[ 1  0  0]
 [ 0  2  0]
 [ 0 10  3]]


## Slicing

In [ ]:
a=np.arange(10)
print(a[1:10:2])

[1 3 5 7 9]


In [ ]:
b=np.arange(10)
b[5:]=10#assigns 10 from index 5 to end
print(b)

[ 0  1  2  3  4 10 10 10 10 10]


# Copies and Viwes

In [ ]:
a=np.arange(10)
b=a[::2]
np.shares_memory(a,b)

True

In [ ]:
b[0]=10
print(b)
print(a)#a is also updated, since it shares memory location

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [ ]:
c=a[::2].copy()#force the copy
np.shares_memory(a,c)

False

In [ ]:
c[0]=5
print(c)
print(a)

[5 2 4 6 8]
[10  1  2  3  4  5  6  7  8  9]


# Fancy Indexing

## Using Boolean Mask

In [ ]:
a=np.random.randint(0,20,15)
print(a)

[ 3  5  6 12  0 18  3 19  6  6  2 12  9  6  3]


In [ ]:
mask=(a % 2 == 0)

In [ ]:
even_numbers=a[mask]
print(even_numbers)

[ 6 12  0 18  6  6  2 12  6]


In [ ]:
a[mask]=-1
print(a)

[ 3  5 -1 -1 -1 -1  3 19 -1 -1 -1 -1  9 -1  3]


## Using Integer Array

In [ ]:
a=np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [ ]:
b=a[[2,3,5,2,4]]
print(b)

[20 30 50 20 40]


In [ ]:
a[[9,7]]= -200
print(a)
print(b)

[   0   10   20   30   40   50   60 -200   80 -200]
[20 30 50 20 40]


# Numerical operations

## Element Wise Operation

In [ ]:
a=np.arange(10)
print(a+1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(a ** 2)

[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
b=np.ones(10) + 1
print("b=",b)
print("a-b =",a-b)

b= [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
a-b = [-2. -1.  0.  1.  2.  3.  4.  5.  6.  7.]


In [ ]:
#Matrix multiplication
c=np.diag([1,2,3,4])
print(c)
print("*"*100)
print(c*c)
print("*"*100)
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
****************************************************************************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************************************************************************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [ ]:
#element comparison
a=np.array([1,2,5,4])
b=np.array([6,2,9,4])

print(a==b)


[False  True False  True]


In [ ]:
print(a>b)
print(a<b)

[False False False False]
[ True False  True False]


In [ ]:
#array wise comparison
print(np.array_equal(a,b))

False


In [ ]:
c=np.array([1,2,5,4])
print(np.array_equal(a,c))

True


## Logical operations

In [ ]:
a=np.array([1,0,0,1],dtype='bool')
b=np.array([0,1,0,1],dtype='bool')
print(np.logical_or(a,b))

[ True  True False  True]


In [ ]:
print(np.logical_and(a,b))
print(np.logical_not(a,b))


[False False False  True]
[False  True  True False]


### Transcendental functions

In [ ]:
a=np.arange(5)+1
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(np.log(a))
print(np.exp(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Shape Mismatch

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,10])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions

In [ ]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [ ]:
y=np.array([[1,2],[3,4]])
print(y)
print("*"*100)
print(y.T)

[[1 2]
 [3 4]]
****************************************************************************************************
[[1 3]
 [2 4]]


In [ ]:
print(y.sum(axis=0))#column wise addition
print(y.sum(axis=1))#row wise addition

[4 6]
[3 7]


In [ ]:
print(y.max())
print(y.argmin())#index of minimum element
print(y.argmax())#index of maximum element

4
0
3


## Logical Reductions

In [ ]:
print(np.all([True,False,False]))#logical and
print(np.any([True,False,False]))#logical or

False
True


In [ ]:
a=np.zeros((50,50))
print(np.any(a!=0))#checks weather any element in an is not equal zero

False


## Statistics

In [ ]:
x=np.arange(1,10)
print(np.mean(x))

5.0


In [ ]:
print(np.median(x))

5.0


In [ ]:
y=np.array([[1,2,3],[4,5,6]])
print(np.mean(y,axis=0))#columnwise mean
print(np.mean(y,axis=1))#row wise mean

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
print(np.std(x))

2.581988897471611


In [ ]:
#ex1
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#ex2
b = np.arange(2, 11).reshape(3, 3)
print(b)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#ex3
x = np.array([[4,6], [2,1]])
print(x)
print("*"*50)
print(np.sort(x, axis=0))
print("*"*50)
print(np.sort(x, axis=1))

[[4 6]
 [2 1]]
**************************************************
[[2 1]
 [4 6]]
**************************************************
[[4 6]
 [1 2]]


In [ ]:
#ex4
arr = np.array([[10,20,30], [20,40,50]])
farr= arr.flatten()
print(farr)
print(farr.flags)
farr.flags['C_CONTIGUOUS']


[10 20 30 20 40 50]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



True

In [2]:
dates = np.arange('2017-03-01', '2017-04-01', dtype='datetime64[D]')

for date in dates:
  print(date)


2017-03-01
2017-03-02
2017-03-03
2017-03-04
2017-03-05
2017-03-06
2017-03-07
2017-03-08
2017-03-09
2017-03-10
2017-03-11
2017-03-12
2017-03-13
2017-03-14
2017-03-15
2017-03-16
2017-03-17
2017-03-18
2017-03-19
2017-03-20
2017-03-21
2017-03-22
2017-03-23
2017-03-24
2017-03-25
2017-03-26
2017-03-27
2017-03-28
2017-03-29
2017-03-30
2017-03-31
